version: '3.8'

services:
  api:
    build: .
    container_name: email-api
    ports:
      - "18301:8000"
    volumes:
      - ./templates:/app/templates
      - ./attachments:/app/attachments
      - ./logs:/app/logs
      
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s